[package]
name = "prust"
version = "0.1.0"
authors = ["ImFlog <garcia.florian.perso@gmail.com>", "NugetChar <nugetchar@gmail.com>"]
edition = "2018"

[dependencies]
yew = "0.15"
web-sys = "0.3.39"
# yew = {version = "0.15", features=["console"]}

# stdweb = "0.4.20"