[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.dev]
run_task = [
    { name = ["build", "wasm-bind"] }
]
watch = true

[tasks.build]
command = "cargo"
args = [
    "build",    
    "--features=console_error_panic_hook",
    "--target=wasm32-unknown-unknown"
]

[tasks.wasm-bind]
script = [
    "wasm-bindgen --target web --no-typescript --out-dir static/ --out-name app target/wasm32-unknown-unknown/debug/prust.wasm"
]

[tasks.serve]
script = [
    "cd static/",
    "python3 -m http.server"
]